# Generated by Django 4.1.1 on 2022-10-04 09:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dev", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, default="default.jpg", max_length=255, null=True
            ),
        ),
    ]
